version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_PORT=${API_PORT}
      - JWT_APP_NAME=${JWT_APP_NAME}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}
      - USERNAME_ADMIN=${USERNAME_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - IMAGE_PATH=${IMAGE_PATH}
    ports:
      - "5432:5432"
    networks:
      - gardio_network
    restart: always
  db:
    image: postgres:alpine3.17
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gardio_network
volumes:
  db-data:
networks:
  gardio_network: